= TickTask - User Guide
:toc:
:toc-title:
:toc-placement: preamble
:sectnums:
:imagesDir: images
:experimental:
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
endif::[]

By: `T01-T1`      Since: `Jun 2017`      Licence: `MIT`

== Quick Start

.  Ensure you have Java version `1.8.0_60` or later installed in your Computer.
+
[NOTE]
Having any Java 8 version is not enough. +
This app will not work with earlier versions of Java 8.
+

== Features

=== Viewing help : `help`
Displays the list of commands available.

Format: `help`

=== Adding a person: `add`
Adds a person to the address book. +

Format: `add [task name] [date due] [start - end]`
        (Note: arguments for add can be inserted in any order)

Examples:
* `add complete tutorial 22/08 5.30 - 6`
* `add 22/08/2017 complete tutorial 5.30`
* `add 22/08/17 5.30 - 6 complete tutorial

=== Editing a Task : `edit`
Edits an existing person in the address book. +

Format: `edit [task name] [new value]`
        (Note: [new value] can be either be 'name', 'date', 'time')

Examples:
* `edit tutorial tut` +
Edits the task named tutorial to tut.
* `edit tutorial 22/09` +
Edits the task's date to 22/09.
* `edit tutorial 5 - 6` +
Edits the task's start timr and end time to 0500 and 0600
* `edit tutorial 5` +
Edits the task's start time to 0500.

=== Deleting a Task: `delete`
Deletes a task from the task manager. +

Format: `delete [task name]`

Examples:
* `delete tutorial` +
Deletes the task named tutorial`

=== Completing a Task : `complete`
Marks a task as complete in the task manager. +

Format: `complete [task name]`

Examples:
* `complete tutorial` +
The task tutorial is marked as complete.

=== Undo/ Redo Actions: `undo` `redo`
Undo or redo the latest action. +

Format: `undo` or `redo`

Examples:
* `undo` +
Undo the previous action such as add, delete, edit or complete.
* `Redo` +
Redo the undo action

=== Specify Storage Folder : `folder`
Specify folder to store all task manager data. +

Format: `Folder [path]`

Examples:
* `folder c://user/documents/taskmanager`

=== Listing All Tasks : `list` `list all`
Displays pending tasks within task manager. To display completed tasks as well, add 'all' to the list comand. +

Format: `list` or 'list all'

Examples:
* `list` +
Displays pending tasks.
* `list all` +
Displays pending and completed tasks.

=== Search Tasks : `search`
Searches for task based on keyword.

Format: `search [keyword]`

Examples:
* `search tutorial` +
* `search 22/08` +
* `search 3` +
Keyword can be either 'date', 'titlr', or 'duration'

== FAQ

== Command Summary

